"""add phone_classifier_override to drill_items

Revision ID: 2a0405d370d8
Revises: caf73903f65a
Create Date: 2026-07-29 15:18:32.556067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0405d370d8'
down_revision: Union[str, None] = 'caf73903f65a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drill_items', sa.Column('phone_classifier_override', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drill_items', 'phone_classifier_override')
    # ### end Alembic commands ###
