"""init schema

Revision ID: 6d2405bb6c78
Revises: 
Create Date: 2026-07-25 21:10:23.014671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2405bb6c78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('word_content',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=False),
    sa.Column('ipa', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language', 'level', 'word', name='uq_word_content_entry')
    )
    op.create_index(op.f('ix_word_content_language'), 'word_content', ['language'], unique=False)
    op.create_table('children',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('badges', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_parent_id'), 'children', ['parent_id'], unique=False)
    op.create_table('drill_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drill_sessions_child_id'), 'drill_sessions', ['child_id'], unique=False)
    op.create_table('phoneme_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.Column('phoneme', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('incorrect', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'phoneme', 'language', 'date', name='uq_phoneme_log_day')
    )
    op.create_index(op.f('ix_phoneme_logs_child_id'), 'phoneme_logs', ['child_id'], unique=False)
    op.create_table('drill_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('item_index', sa.Integer(), nullable=False),
    sa.Column('target_word', sa.String(length=200), nullable=False),
    sa.Column('target_ipa', sa.String(length=200), nullable=False),
    sa.Column('child_audio_url', sa.String(), nullable=True),
    sa.Column('child_transcript', sa.String(length=200), nullable=True),
    sa.Column('child_ipa', sa.String(length=200), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('error_type', sa.String(length=30), nullable=True),
    sa.Column('attempt_num', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['drill_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drill_items_session_id'), 'drill_items', ['session_id'], unique=False)
    op.create_table('parent_tips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('tip_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['drill_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_tips_session_id'), 'parent_tips', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_tips_session_id'), table_name='parent_tips')
    op.drop_table('parent_tips')
    op.drop_index(op.f('ix_drill_items_session_id'), table_name='drill_items')
    op.drop_table('drill_items')
    op.drop_index(op.f('ix_phoneme_logs_child_id'), table_name='phoneme_logs')
    op.drop_table('phoneme_logs')
    op.drop_index(op.f('ix_drill_sessions_child_id'), table_name='drill_sessions')
    op.drop_table('drill_sessions')
    op.drop_index(op.f('ix_children_parent_id'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_word_content_language'), table_name='word_content')
    op.drop_table('word_content')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
