"""drill item errors as json

Revision ID: caf73903f65a
Revises: 6d2405bb6c78
Create Date: 2026-07-25 21:53:09.609532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf73903f65a'
down_revision: Union[str, None] = '6d2405bb6c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drill_items', sa.Column('errors', sa.JSON(), nullable=False))
    op.drop_column('drill_items', 'error_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drill_items', sa.Column('error_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('drill_items', 'errors')
    # ### end Alembic commands ###
